### ISSUE TITLE
Please Do not Assume the Value of Magic Header

### ISSUE THREAD

**Issue by benbini** [weaknespase/toxana-tkit#1]
Looking at some .pkg files from the Chinese port of Sen No Kiseki.  It is dangerous to assume that the 4-byte magic header will be set to 0, as you do in pkg_tool.js:

```javascript
//Using first four bytes as marker, since every file i've seen has them set to 0
if (buf.readUInt32LE(0) == 0x0) {
     var records = buf.readUInt32LE(4);
     var pos = read, bofs = 0;
      //Sanity check, file length must be greater than or equal to expected length of header
```

Some .pkg files have those magic bytes (or whatever they are) set to non-zero values, e.g. "book.pkg" from the Chinese port of Sen no Kiseki 1 for Vita:

```text
         00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f 
         -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
000000 | 8f f9 86 53 04 00 00 00 62 6f 6f 6b 30 30 2e 64 | ...S....book00.d
000010 | 61 74 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | at..............
000020 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................
000030 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................
000040 | 00 00 00 00 00 00 00 00 ef c7 00 00 0d 73 00 00 | .............s..
```

Until the function of those four bytes is better understood you might want to just eat the 4 bytes and move on, along the lines of :

```javascript
             //Using first four bytes as marker, since every file i've seen has them set to 0
//            if (buf.readUInt32LE(0) == 0x0) {
              if (buf.readUInt32LE(4)) {
                 var records = buf.readUInt32LE(4);
                 var pos = read, bofs = 0;
```

The tool works great otherwise.  Thanks for sparing me the pain of implementing the lz77 decompression.

**Comment by weaknespase** [comment]
Are the bytes different in different files?

Can you run adler32 and crc32 functions on your pkg file with first four bytes set to zero and with them cut altogether? I think it should be a checksum.

I consider extending heuristic safeguards to avoid parsing invalid files in next version, thank you for the input.

**Comment by benbini** [comment]
It actually looks more like a counter of some kind. Here's a dump from a closely related file (scena.pkg):

```text
         00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f 
         -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
000000 | 90 f9 86 53 41 01 00 00 61 30 30 30 30 2e 64 61 | ...SA...a0000.da
000010 | 74 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | t...............
000020 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................
000030 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................
000040 | 00 00 00 00 00 00 00 00 1f 06 03 00 71 e8 01 00 | ............q...
```

I haven't looked at any more than those two, but even without running checksums on them I'd think there'd be more variance if that's what these were.  No idea why all of yours are set to 0...

**Comment by weaknespase** [comment]
Oh, i think i know for what it used - it's a patch counter, just a sequential id of built package to quickly differentiate between versions. Thank you for the research, i'll make a change in version 1.2.
