### ISSUE TITLE
Please Check Decompression Logic for When Flags == 0x3

### ISSUE THREAD

**Issue by benbini** [weaknespase/toxana-tkit#2]
Hello, I have run into another issue using this tool, when using it to decompress Falcom PKGs containing files with `FLAG_LOCAL_HDR` set.  For example when I run the tool against the files in `scena.pkg` for  Sen II (Vita) Chinese localization such as the following:
```json
{
  "flags": 3,
  "uncompressed_size": 111521,
  "compressed_size": 75518,
  "data_offset_hex": "0x30DDEA",
  "name": "t0001.dat",
  "data_offset": 3202538
}
```
Use of pkg_tool.js returns a file of size 76962 bytes, much smaller than the expected `uncompressed_size`, and inspection of the file confirms that there is content that is not being decompressed/decompressed incorrectly.  A Python [re-implementation](https://pastebin.com/axLaGfuP) of the core decompression logic results in correct (wrt expected size and observed structure) decompressed streams.

**Comment by weaknespase** [comment]
I double that, i also found a bug in decompressor earlier, thank you for the input. Would be fixed in the next version of toolset.

**Comment by weaknespase** [comment]
Tested new version of stream-based decompressor on various files, now works fine.
