### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by Makein** [weaknespase/toxana-tkit#3]
I dl sourse code install node js 6 and try to run line
npm i -g git+https://github.com/weaknespase/toxana-tkit.git

I have W7 and can't figure it's out

**Comment by weaknespase** [comment]
Now you should have it installed in the system and usable globally in the command line prompt. There are several tools `tx-pkgarg`, `tx-tblconv`, `ut-pckarc` and `ut-fileconv` that should be available to you.
